socialmedia/posts/urls.py
from django.urls import re_path

from . import views

app_name='posts'

urlpatterns = [
    re_path(r"^$", views.PostList.as_view(), name="all"),
    re_path(r"new/$", views.CreatePost.as_view(), name="create"),
    re_path(r"by/(?P<username>[-\w]+)/$",views.UserPost.as_view(),name="for_user"),
    re_path(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    re_path(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
    re_path(r'upvote/(?P<pk>\d+)/$', views.Upvote.as_view(), name='upvote'),
    re_path(r'downvote/(?P<pk>\d+)/$', views.Downvote.as_view(), name='downvote')
]

socialmedia/socialmedia/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$',views.HomePage.as_view(),name='home'),
    re_path(r'^accounts/',include('accounts.urls',namespace='accounts')),
    re_path(r'^accounts/',include('django.contrib.auth.urls')),
    re_path(r'^test/$',views.TestPage.as_view(),name='test'),
    re_path(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    re_path(r'^posts/',include('posts.urls',namespace='posts')),
    re_path(r'^groups/',include('groups.urls',namespace='groups'))
]

socialmedia/posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

from markdown import markdown
from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name='posts', null=True, blank=True, on_delete=models.DO_NOTHING)
    members = models.ManyToManyField(User, through='Vote')
    objects = models.Manager()

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = markdown(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username':self.user.username, 'pk':self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'message']

class Vote(models.Model):
    user = models.ForeignKey(User, related_name='user_votes', on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='votes', on_delete=models.DO_NOTHING)
    objects = models.Manager()

    def __str__(self):
        return self.user

    class Meta:
        unique_together = ('user', 'post')

socialmedia/posts/views.py
# from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
from django.http import Http404
from django.views import generic
from groups.models import Group
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.db import IntegrityError
from braces.views import SelectRelatedMixin

from . import models
from posts.models import Post, Vote
from . import forms

from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.


class PostList(SelectRelatedMixin,generic.ListView):
    model = models.Post
    select_related = ('user', 'group')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_groups"] = Group.objects.filter(members__in=[self.request.user])
        context["all_groups"] = Group.objects.all()
        return context


class UserPost(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))

        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))


class CreatePost(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):
    fields = ('message','group')
    model = models.Post

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post deleted')
        return super().delete(*args, **kwargs)


class Downvote(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        # return reverse('posts:single', kwargs={'pk': self.kwargs.get('pk')})
        return reverse_lazy('posts:all')

    def get(self, request, *args, **kwargs):
        try:
            votes = models.Vote.objects.filter(
                user=self.request.user, post__pk=self.kwargs.get('pk')
            ).get()

        except models.Vote.DoesNotExist:
            messages.warning(self.request, 'Sorry you are not allowed for the operation')
        else:
            votes.delete()
        return super().get(self.request, *args, **kwargs)


class Upvote(LoginRequiredMixin,generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        # return reverse('posts:single', kwargs={'pk': self.kwargs.get('pk')})
        return reverse_lazy('posts:all')

    def get(self, request, *args, **kwargs):
        post = get_object_or_404(Post, pk=self.kwargs.get('pk'))

        try:
            Vote.objects.create(user=self.request.user, post=post)
        except IntegrityError:
            messages.warning(self.request, 'Already voted')
        else:
            messages.success(self.request, 'Voted!')
        return super().get(self.request, *args, **kwargs)

socialmedia/posts/templates/posts/_post.html
<div class="post media">
	<div class="card" style="border: 1px solid black;">
		<div class="card-header">
    		<small class="text-muted cat">
				<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
</svg>
				<span class="username">By <a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a></span>
				<time class="time">at : <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a></time>
				{% if post.group %}
				<span class="group-name">in <a href="{% url 'groups:single' slug=post.group.name|lower %}">{{ post.group.name }}</a></span>
				{% endif %}
			</small>
  		</div>
	<div class="card-body">
	<h5 class="card-title"> {{ post.message_html|safe }}</h5>
	</div>
	<div class="media-body card-footer">
<!--		<strong>{{ post.user.username }}</strong>-->

		<div class="media-footer">
			{% if user.is_authenticated and post.user == user and not hide_delete %}
				<a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn">
<!--					<span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>-->
<!--					<span class="text-white icon-label">Delete</span>-->
					<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
  <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
Delete</svg>
				</a>
			{% endif %}
			{% if user in post.members.all %}
			<a href="{% url 'posts:downvote' pk=post.pk %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-down-up" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M11.5 15a.5.5 0 0 0 .5-.5V2.707l3.146 3.147a.5.5 0 0 0 .708-.708l-4-4a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L11 2.707V14.5a.5.5 0 0 0 .5.5zm-7-14a.5.5 0 0 1 .5.5v11.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L4 13.293V1.5a.5.5 0 0 1 .5-.5z"/>
</svg> </a> down {{ post.members.count }}
			{% else %}
			<a href="{% url 'posts:upvote' pk=post.pk %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-down-up" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M11.5 15a.5.5 0 0 0 .5-.5V2.707l3.146 3.147a.5.5 0 0 0 .708-.708l-4-4a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L11 2.707V14.5a.5.5 0 0 0 .5.5zm-7-14a.5.5 0 0 1 .5.5v11.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L4 13.293V1.5a.5.5 0 0 1 .5-.5z"/>
</svg></a> {{ post.members.count }}
			{% endif %}
		</div>
	</div>
	</div>
</div>

socialmedia/posts/templates/posts/post_base.html
{% extends 'base.html' %}

{% block content_block %}

<div class="post-page">
    <div class="container">
        <div class="row">
            {% block prepost %} {% endblock %}
            {% block post_content %} {% endblock %}
            {% block post_post %} {% endblock %}
        </div>
    </div>
</div>

{% endblock %}

socialmedia/posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}

{% block post_content %}

<h3>Are you sure you want to delete this post?</h3>

<div class="posts">
    {% include 'posts/_post.html' with post=object hide_delete=True %}
</div>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm delete" class="btn btn-danger btn-large">
    <a class ="btn btn-simple btn-large btn-default" href="{% url 'posts:single' username=user.username pk=object.pk %}">Cancel</a>
</form>

{% endblock %}

socialmedia/posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}

{% block post_content %}
<div class="col-md-8">
    {% include 'posts/_post.html' %}
</div>

{% endblock %}

socialmedia/posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap3 %}

{% block post_content %}
<h4>Create a new Post</h4>
<form id='postForm' action="{% url 'posts:create' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Post" class="btn btn-primary btn-large">

</form>
{% endblock %}

socialmedia/posts/templates/posts/post_list.html
{% extends 'posts/post_base.html' %}

{% block prepost %}
<div class="col-md-4">
    {% if request.user.is_authenticated %}
    <div class="card card-with-shadow">
        <div class="content card card-header">
            <h5>
                Your groups
            </h5>
            <ul class="list-unstyled">
                {% for member_group in user_groups %}
                <li class="group li-with-bullet">
                    <a href="{% url 'groups:single' slug=member_group.slug %}">{{ member_group.slug }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% endif  %}
    <div class="card card-with-shadow">
        <div class="content card card-header">
            <h5 class="'title">All groups</h5>
            <ul class="list-unstyled">
                {% for other_group in all_groups %}
                <li class="group li-with-bullet">
                    <a href="{% url 'groups:single' slug=other_group.slug%}">{{ other_group.slug }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-6">
    {% for post in post_list %}
    {% include "posts/_post.html" %}
    {% endfor %}
</div>
{% endblock %}

socialmedia/posts/templates/posts/user_post_list.html
{% extends 'posts/post_base.html' %}

{% block prepost %}
<div class="col-md-4">
    <h1>@ {{ post_user.username }}</h1>
</div>
{% endblock %}

{% block post_content %}
<div class="content">
    {% for post in post_list %}
    {% include 'posts/_post.html' %}
    {% endfor %}
</div>
{% endblock %}