socialmedia/accounts/urls.py
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from . import views

# Setup app_name variable to use url template
app_name = 'accounts'

urlpatterns = [
    re_path(r'^login/$',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    re_path(r'^logout/$',auth_views.LogoutView.as_view(),name='logout'),
    re_path(r'^signup/$',views.SignUp.as_view(),name='signup'),
]

socialmedia/posts/urls.py
from django.urls import re_path

from . import views

app_name='posts'

urlpatterns = [
    re_path(r"^$", views.PostList.as_view(), name="all"),
    re_path(r"new/$", views.CreatePost.as_view(), name="create"),
    re_path(r"by/(?P<username>[-\w]+)/$",views.UserPost.as_view(),name="for_user"),
    re_path(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    re_path(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
    re_path(r'upvote/(?P<pk>\d+)/$', views.Upvote.as_view(), name='upvote'),
    re_path(r'downvote/(?P<pk>\d+)/$', views.Downvote.as_view(), name='downvote')
]

socialmedia/socialmedia/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$',views.HomePage.as_view(),name='home'),
    re_path(r'^accounts/',include('accounts.urls',namespace='accounts')),
    re_path(r'^accounts/',include('django.contrib.auth.urls')),
    re_path(r'^test/$',views.TestPage.as_view(),name='test'),
    re_path(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    re_path(r'^posts/',include('posts.urls',namespace='posts')),
    re_path(r'^groups/',include('groups.urls',namespace='groups'))
]

socialmedia/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'socialmedia/css/master.css' %}?">

    <title>Social Media</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-light bg-success mynav" role="navigation" id="navbar">
      <div class="container">
        <a class="navbar-brand mynav" href="{% url 'home' %}">My Social Media</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="nav navbar-nav ms-auto">
          {% if user.is_authenticated %}
            <li><a class="btn btn-simple" href="{% url 'posts:all' %}">Posts</a></li>
            <li><a class="btn btn-simple" href="{% url 'posts:create' %}">NewPost</a></li>
            <li><a class="btn btn-simple" href="{% url 'groups:all' %}">Groups</a></li>
            <li><a class="btn btn-simple" href="{% url 'groups:create' %}">Create Group</a></li>
            <li><a class="btn btn-simple" href="{% url 'accounts:logout' %}">Log Out</a></li>
          {% else %}
            <li><a class="btn btn-simple" href="#">Groups</a></li>
            <li><a class="btn btn-simple" href="{% url 'accounts:login' %}">Log In</a></li>
            <li><a class="btn btn-simple" href="{% url 'accounts:signup' %}">Sign Up</a></li>
          {% endif %}

        </ul>
      </div>

      </div>
    </nav>

    <div class="container mycontent">
      {% block content_block %}
      {% endblock %}
    </div>
  <canvas id="canvas"></canvas>
  </body>
<script src="{% static 'socialmedia/js/master.js' %}?" type="text/javascript" ></script>
</html>

socialmedia/templates/index.html
{% extends 'base.html' %}

{% block content_block %}
  <h1>Welcome to social media project!</h1>

{% endblock %}

socialmedia/templates/test.html
{% extends 'base.html' %}

{% block content_block %}
  <h1>You are now logged in!</h1>

{% endblock %}

socialmedia/templates/thanks.html
{% extends 'base.html' %}

{% block content_block %}
  <h1>Thanks for visiting!</h1>

{% endblock %}