socialmedia/groups/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'groups'

urlpatterns = [
    re_path(r'^$',views.ListGroups.as_view(),name='all'),
    re_path(r'^new/$',views.CreateGroup.as_view(),name='create'),
    re_path(r"^posts/in/(?P<slug>[-\w]+)/$",views.SingleGroup.as_view(),name="single"),
    re_path(r'join/(?P<slug>[-\w]+)/$', views.JoinGroup.as_view(), name='join'),
    re_path(r'leave/(?P<slug>[-\w]+)/$', views.LeaveGroup.as_view(), name='leave')
]

socialmedia/posts/urls.py
from django.urls import re_path

from . import views

app_name='posts'

urlpatterns = [
    re_path(r"^$", views.PostList.as_view(), name="all"),
    re_path(r"new/$", views.CreatePost.as_view(), name="create"),
    re_path(r"by/(?P<username>[-\w]+)/$",views.UserPost.as_view(),name="for_user"),
    re_path(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    re_path(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
    re_path(r'upvote/(?P<pk>\d+)/$', views.Upvote.as_view(), name='upvote'),
    re_path(r'downvote/(?P<pk>\d+)/$', views.Downvote.as_view(), name='downvote')
]

socialmedia/socialmedia/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$',views.HomePage.as_view(),name='home'),
    re_path(r'^accounts/',include('accounts.urls',namespace='accounts')),
    re_path(r'^accounts/',include('django.contrib.auth.urls')),
    re_path(r'^test/$',views.TestPage.as_view(),name='test'),
    re_path(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    re_path(r'^posts/',include('posts.urls',namespace='posts')),
    re_path(r'^groups/',include('groups.urls',namespace='groups'))
]

socialmedia/groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

from markdown import markdown

from django.contrib.auth import get_user_model
User = get_user_model()

# from django.contrib.auth.models import User

from django import template
register = template.Library()

# Create your models here.


class Group(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User, through='GroupMember')
    objects = models.Manager()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name=self.name.capitalize()
        self.slug = slugify(self.name.capitalize())
        self.description_html = markdown(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='membership', on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.DO_NOTHING)
    objects = models.Manager()

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

socialmedia/groups/views.py
from django.db import IntegrityError
from django.core.exceptions import ObjectDoesNotExist
# from django.shortcuts import render

from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.urls import reverse
from django.views import generic
from django.contrib import messages
from django.shortcuts import get_object_or_404
from groups.models import Group, GroupMember
from . import models
# Create your views here.


class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Group


class SingleGroup(generic.DetailView):
    model = Group


class ListGroups(generic.ListView):
    model = Group


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        try:
            membership = models.GroupMember.objects.filter(
                user=self.request.user, group__slug=self.kwargs.get('slug')
            ).get()

        except models.GroupMember.DoesNotExist:
            messages.warning(self.request, 'Sorry you are not a member of this group')
        else:
            membership.delete()
            messages.success(self.request, 'You have left the group!')
        return super().get(self.request, *args, **kwargs)


class JoinGroup(LoginRequiredMixin,generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user, group=group)
        except IntegrityError:
            messages.warning(self.request, 'Already a member')
        else:
            messages.success(self.request, 'You are now a member')
        return super().get(self.request, *args, **kwargs)

socialmedia/groups/templates/groups/group_base.html
{% extends 'base.html' %}

{% block content_block %}
    <div class="container">
        <div class="row">
            {% block pregroup %}{% endblock %}
            {% block group_content %}{% endblock %}
            {% block postgroup %}{% endblock %}
        </div>
    </div>

{% endblock %}

socialmedia/groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
<div class="content">
<div class="card" style="border: 2px solid black;">
    <div class="card-header">
    <h1>{{ group.name }} </h1>
    </div>
    <div class="card-body">
    <h2><svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
  <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
</svg> {{ group.members.count }}</h2>
        <i class='far fa-id-badge'></i>
    <div class="content">
        {% if user in group.members.all %}
            <a href="{% url 'groups:leave' slug=group.slug %}"
               class="btn btn-lg btn-fill btn-warning"><span
                    class="glyphicon glyphicon-remove-circle"></span> Leave </a>
        {% else %}
            <a href="{% url 'groups:join' slug=group.slug %}"
               class="btn btn-lg btn-fill btn-warning"><span
                    class="glyphicon glyphicon-ok-circle"></span> Join </a>
        {% endif %}
    </div>
    </div>
</div>
</div>
{% endblock %}

{% block group_content %}
    <div class="content">
        {% if group.posts.count == 0 %}
	    <h2>No posts in this group yet!</h2>

	    {% else %}

		{% for post in group.posts.all %}
			{% include "posts/_post.html" %}
		{% endfor %}

	    {% endif %}
    </div>

{% endblock %}

socialmedia/groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load bootstrap3 %}

{% block group_content %}
<h4>Create a new group!</h4>
<form action="{% url 'groups:create' %}" method="POST" id="groupForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Create" class="btn btn-primary btn-large">
</form>
{% endblock %}

socialmedia/groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
    <div class="col-md-4 card">
        <div class="content card-header">
            {% if user.is_authenticated %}
                <h2> Welcome Back!
                    <a href="{% url 'posts:for_user' username=user.username %}">
                        @{{ user.username }}
                    </a>
                </h2>
            {% endif %}
            <p>Welcome to the groups page!</p>
        </div>
        {% if user.is_authenticated %}
            <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning">
                <span class="glyphicon glyphicon-plus-sign"></span> Create new group!
            </a>
        {% endif %}
    </div>
{% endblock %}

{% block group_content %}
    <div class="col-md-8">
        <div class="list-group card">
            {% for group in object_list %}
            <a class ="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
                <div class="card-header">
                <h3 class="title list-group-item-heading"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-collection" viewBox="0 0 16 16">
  <path d="M2.5 3.5a.5.5 0 0 1 0-1h11a.5.5 0 0 1 0 1h-11zm2-2a.5.5 0 0 1 0-1h7a.5.5 0 0 1 0 1h-7zM0 13a1.5 1.5 0 0 0 1.5 1.5h13A1.5 1.5 0 0 0 16 13V6a1.5 1.5 0 0 0-1.5-1.5h-13A1.5 1.5 0 0 0 0 6v7zm1.5.5A.5.5 0 0 1 1 13V6a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-.5.5h-13z"/>
</svg> {{ group.name|title }}</h3>
                </div>
                <div class="list-group-item-text container-fluid card-body">
                    {{ group.description_html|safe }}
                    <div class="row">
                        <div class="col-md-4">
                            <span class="badge bg-secondary">{{ group.members.count }}</span>
                            member {{ group.members.count|pluralize }}
                        </div>
                        <div class="col-md-4">
                            <span class="badge bg-secondary">{{ group.posts.count }}</span>
                            posts {{ group.posts.count|pluralize }}
                        </div>
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}